= Gaining Efficiencies in the Transport of Structured Descriptions of Marine Data Observations between Knowledge Curators

__We seek to hold a workshop to develop an efficient and sustainable workflow to efficiently share structured descriptions of marine data observations.  The workflow will align the efforts of data curators, curators of authoritative thesauri, and knowledge modelers developing reference ontologies.  Each of the workflow’s three agents act as curators of knowledge within their own organizational structures with processes that work for governing structured data.  However, the exchange of this information between organizations creates a new virtual organization[1] that needs its own effective workflows for sending, receiving and digesting structured data.  This latter case is likely to grow more dominant in the emerging world of linked and distributed data; thus, developing stable inter-organizational workflows is a priority.  The workshop will not focus on the internal process of each agent, but on the transport vectors between agents to ensure efficient delivery and assimilation of data with respect to each agent’s internal governance needs.  As a result, the information exchange between these types of agents enables a new capability in science to deliver outcomes that meet initiatives such as United Nations - Sustainable Development Goals (SDGs)[2], Global Ocean Observing System - Essential Ocean Variables (EOVs)[3], and the Group on Earth Observations - Essential Biodiversity Variables (EBVs)[4].__

== Background

Information sharing, synthesis, and packaging is critical to delivering knowledge in multi-disciplinary contexts within research, but even more so when engaging with multi-stakeholder, cross-cutting initiatives like the EOVs, EBVs, and SDGs.  To do so, machine-readable ontologies harmonizing the meaning (i.e. semantics) behind each stakeholder’s terminology and metadata are required to deliver accurate information to these initiatives.  However, the development of high quality ontologies often cannot keep pace with the complete volume of observation types created in modern, integrative data systems. .  However, we have realized that a system combining 1) ontologies to handle semantically dense or problematic terminology and 2) authoritative thesauri to thematically describe and categorize more straightforward observations, will provide a basis to boost FAIRness in a practical and sustainable way .   In this system, ontologies interface with data curators and thesauri developers when the rich, machine-readable expressiveness of their ontologies is needed to resolve ambiguity or allow more flexible information handling than thesauri can provide. Further,  analytics term usage in the system can identify popular thesauri terms as high-value targets for ontologies to expand on. .  Consequently, the most active, day-to-day interface in this system is that between data curators and thesauri. Here, there is a need for efficiency gains that respect the governance processes of the thesauri, but deliver expedited results for data curators, leveraging tools for automatic term creation along constrained semantic frameworks (which ease coordination with ontology developers). As a result, the thesauri become the structured glue between instance data held by curators and the reference ontologies for delivering the outcomes required by SDGs, EOVs, and research themes.

== Expected Results

* A prototype for information exchange pathways and synchronized activity between the three agents
** A workflow for data curators to operate within the thesauri framework to constructing the elements of an observations to consistently arrive at existing terms of the, at least, the components for minting a new term
** An	 expedient transport mechanism between data curators and thesauri for initiating the minting of new terms and harvesting the newly minted term by the curators.
** A defined mechanism for delivering groups of thesauri terms to ontologists that can be used to extend reference ontologies while preserving links to thesauri 
** A defined mechanism for data and thesauri curators to request ontologists to support them unpacking and creating ontology classes for semantically dense or problematic terms to ensure clarity across disciplines and stakeholders
** An announcement mechanism for ontologists, for thesauri curators and data curators about new models related to thesauri terms
* An identification of a few example outcomes to test the prototype. (How do we meet a specific EOV, research theme, etc.)
* Outline of the concept, scale, approach, and potential outcomes to appeal to funding agencies with an elevator pitch for a project
